namespace BuilderGenerator;

internal static class BuilderGeneratorHelper
{
    internal const string Header = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    // This won't work if users have [InternalsVisibleTo] attributes and are using the source generator in multiple projects.
    internal const string AttributeText = @"
using System;

namespace BuilderGenerator;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class BuildableAttribute : Attribute { }

";
}
