using System;
using System.Collections.Generic;
using System.Text;

namespace BuilderGenerator;

internal static class BuilderGeneratorHelper
{
    internal const string Header = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    internal const string AttributeText = @"
using System;

namespace BuilderGenerator;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class BuildableAttribute : Attribute { }

";
}
